# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker image and run end-to-end tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
    - name: Run end-to-end tests
      run: >
        docker compose --profile testing up 
        --build 
        --exit-code-from test-service
    - name: Login to Dokcer Hub
      uses: docker/login-action@v2
      if: ${{ github.event_name == 'push' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image to Docker Hub
      uses: docker/build-push-action@v4.0.0
      if: ${{ github.event_name == 'push' }}
      with:
        context: ./web
        push: true
        tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/swetan/page-tracker:4f3934b625ae6cf32d
